/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileSettingsRouteImport } from './routes/profile-settings'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoggedOutRouteImport } from './routes/logged-out'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableEditorEditRouteImport } from './routes/table-editor/edit'
import { Route as TableEditorAddRouteImport } from './routes/table-editor/add'
import { Route as HrTrainingRouteImport } from './routes/hr/training'
import { Route as HrRecruitmentRouteImport } from './routes/hr/recruitment'
import { Route as HrPerformanceRouteImport } from './routes/hr/performance'
import { Route as HrLeaveRouteImport } from './routes/hr/leave'
import { Route as HrDisciplinaryRouteImport } from './routes/hr/disciplinary'
import { Route as HrCompensationRouteImport } from './routes/hr/compensation'
import { Route as FinanceVehiclesRouteImport } from './routes/finance/vehicles'
import { Route as FinanceTravelRouteImport } from './routes/finance/travel'
import { Route as FinanceTimesheetsRouteImport } from './routes/finance/timesheets'
import { Route as FinanceStockRouteImport } from './routes/finance/stock'
import { Route as FinanceProcurementRouteImport } from './routes/finance/procurement'
import { Route as FinancePettyCashRouteImport } from './routes/finance/petty-cash'
import { Route as FinancePaymentsRouteImport } from './routes/finance/payments'
import { Route as FinanceMissionsRouteImport } from './routes/finance/missions'
import { Route as FinanceFuelRouteImport } from './routes/finance/fuel'
import { Route as FinanceFraudRouteImport } from './routes/finance/fraud'
import { Route as FinanceAuditRouteImport } from './routes/finance/audit'
import { Route as FinanceAuctionsRouteImport } from './routes/finance/auctions'
import { Route as FinanceAssetsRouteImport } from './routes/finance/assets'
import { Route as HrLeaveEditRouteImport } from './routes/hr/leave/edit'
import { Route as HrLeaveAddRouteImport } from './routes/hr/leave/add'
import { Route as FinanceFraudEditRouteImport } from './routes/finance/fraud/edit'
import { Route as FinanceFraudAddRouteImport } from './routes/finance/fraud/add'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile-settings',
  path: '/profile-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedOutRoute = LoggedOutRouteImport.update({
  id: '/logged-out',
  path: '/logged-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableEditorEditRoute = TableEditorEditRouteImport.update({
  id: '/table-editor/edit',
  path: '/table-editor/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TableEditorAddRoute = TableEditorAddRouteImport.update({
  id: '/table-editor/add',
  path: '/table-editor/add',
  getParentRoute: () => rootRouteImport,
} as any)
const HrTrainingRoute = HrTrainingRouteImport.update({
  id: '/hr/training',
  path: '/hr/training',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRecruitmentRoute = HrRecruitmentRouteImport.update({
  id: '/hr/recruitment',
  path: '/hr/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPerformanceRoute = HrPerformanceRouteImport.update({
  id: '/hr/performance',
  path: '/hr/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveRoute = HrLeaveRouteImport.update({
  id: '/hr/leave',
  path: '/hr/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDisciplinaryRoute = HrDisciplinaryRouteImport.update({
  id: '/hr/disciplinary',
  path: '/hr/disciplinary',
  getParentRoute: () => rootRouteImport,
} as any)
const HrCompensationRoute = HrCompensationRouteImport.update({
  id: '/hr/compensation',
  path: '/hr/compensation',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceVehiclesRoute = FinanceVehiclesRouteImport.update({
  id: '/finance/vehicles',
  path: '/finance/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTravelRoute = FinanceTravelRouteImport.update({
  id: '/finance/travel',
  path: '/finance/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceTimesheetsRoute = FinanceTimesheetsRouteImport.update({
  id: '/finance/timesheets',
  path: '/finance/timesheets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceStockRoute = FinanceStockRouteImport.update({
  id: '/finance/stock',
  path: '/finance/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceProcurementRoute = FinanceProcurementRouteImport.update({
  id: '/finance/procurement',
  path: '/finance/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePettyCashRoute = FinancePettyCashRouteImport.update({
  id: '/finance/petty-cash',
  path: '/finance/petty-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceMissionsRoute = FinanceMissionsRouteImport.update({
  id: '/finance/missions',
  path: '/finance/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFuelRoute = FinanceFuelRouteImport.update({
  id: '/finance/fuel',
  path: '/finance/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceFraudRoute = FinanceFraudRouteImport.update({
  id: '/finance/fraud',
  path: '/finance/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAuditRoute = FinanceAuditRouteImport.update({
  id: '/finance/audit',
  path: '/finance/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAuctionsRoute = FinanceAuctionsRouteImport.update({
  id: '/finance/auctions',
  path: '/finance/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAssetsRoute = FinanceAssetsRouteImport.update({
  id: '/finance/assets',
  path: '/finance/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const HrLeaveEditRoute = HrLeaveEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HrLeaveRoute,
} as any)
const HrLeaveAddRoute = HrLeaveAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HrLeaveRoute,
} as any)
const FinanceFraudEditRoute = FinanceFraudEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FinanceFraudRoute,
} as any)
const FinanceFraudAddRoute = FinanceFraudAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => FinanceFraudRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user': typeof UserRoute
  '/finance/assets': typeof FinanceAssetsRoute
  '/finance/auctions': typeof FinanceAuctionsRoute
  '/finance/audit': typeof FinanceAuditRoute
  '/finance/fraud': typeof FinanceFraudRouteWithChildren
  '/finance/fuel': typeof FinanceFuelRoute
  '/finance/missions': typeof FinanceMissionsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/petty-cash': typeof FinancePettyCashRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/stock': typeof FinanceStockRoute
  '/finance/timesheets': typeof FinanceTimesheetsRoute
  '/finance/travel': typeof FinanceTravelRoute
  '/finance/vehicles': typeof FinanceVehiclesRoute
  '/hr/compensation': typeof HrCompensationRoute
  '/hr/disciplinary': typeof HrDisciplinaryRoute
  '/hr/leave': typeof HrLeaveRouteWithChildren
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/training': typeof HrTrainingRoute
  '/table-editor/add': typeof TableEditorAddRoute
  '/table-editor/edit': typeof TableEditorEditRoute
  '/finance/fraud/add': typeof FinanceFraudAddRoute
  '/finance/fraud/edit': typeof FinanceFraudEditRoute
  '/hr/leave/add': typeof HrLeaveAddRoute
  '/hr/leave/edit': typeof HrLeaveEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user': typeof UserRoute
  '/finance/assets': typeof FinanceAssetsRoute
  '/finance/auctions': typeof FinanceAuctionsRoute
  '/finance/audit': typeof FinanceAuditRoute
  '/finance/fraud': typeof FinanceFraudRouteWithChildren
  '/finance/fuel': typeof FinanceFuelRoute
  '/finance/missions': typeof FinanceMissionsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/petty-cash': typeof FinancePettyCashRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/stock': typeof FinanceStockRoute
  '/finance/timesheets': typeof FinanceTimesheetsRoute
  '/finance/travel': typeof FinanceTravelRoute
  '/finance/vehicles': typeof FinanceVehiclesRoute
  '/hr/compensation': typeof HrCompensationRoute
  '/hr/disciplinary': typeof HrDisciplinaryRoute
  '/hr/leave': typeof HrLeaveRouteWithChildren
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/training': typeof HrTrainingRoute
  '/table-editor/add': typeof TableEditorAddRoute
  '/table-editor/edit': typeof TableEditorEditRoute
  '/finance/fraud/add': typeof FinanceFraudAddRoute
  '/finance/fraud/edit': typeof FinanceFraudEditRoute
  '/hr/leave/add': typeof HrLeaveAddRoute
  '/hr/leave/edit': typeof HrLeaveEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/logged-out': typeof LoggedOutRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/profile-settings': typeof ProfileSettingsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user': typeof UserRoute
  '/finance/assets': typeof FinanceAssetsRoute
  '/finance/auctions': typeof FinanceAuctionsRoute
  '/finance/audit': typeof FinanceAuditRoute
  '/finance/fraud': typeof FinanceFraudRouteWithChildren
  '/finance/fuel': typeof FinanceFuelRoute
  '/finance/missions': typeof FinanceMissionsRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/finance/petty-cash': typeof FinancePettyCashRoute
  '/finance/procurement': typeof FinanceProcurementRoute
  '/finance/stock': typeof FinanceStockRoute
  '/finance/timesheets': typeof FinanceTimesheetsRoute
  '/finance/travel': typeof FinanceTravelRoute
  '/finance/vehicles': typeof FinanceVehiclesRoute
  '/hr/compensation': typeof HrCompensationRoute
  '/hr/disciplinary': typeof HrDisciplinaryRoute
  '/hr/leave': typeof HrLeaveRouteWithChildren
  '/hr/performance': typeof HrPerformanceRoute
  '/hr/recruitment': typeof HrRecruitmentRoute
  '/hr/training': typeof HrTrainingRoute
  '/table-editor/add': typeof TableEditorAddRoute
  '/table-editor/edit': typeof TableEditorEditRoute
  '/finance/fraud/add': typeof FinanceFraudAddRoute
  '/finance/fraud/edit': typeof FinanceFraudEditRoute
  '/hr/leave/add': typeof HrLeaveAddRoute
  '/hr/leave/edit': typeof HrLeaveEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/logged-out'
    | '/login'
    | '/otp'
    | '/profile-settings'
    | '/reports'
    | '/reset-password'
    | '/user'
    | '/finance/assets'
    | '/finance/auctions'
    | '/finance/audit'
    | '/finance/fraud'
    | '/finance/fuel'
    | '/finance/missions'
    | '/finance/payments'
    | '/finance/petty-cash'
    | '/finance/procurement'
    | '/finance/stock'
    | '/finance/timesheets'
    | '/finance/travel'
    | '/finance/vehicles'
    | '/hr/compensation'
    | '/hr/disciplinary'
    | '/hr/leave'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/training'
    | '/table-editor/add'
    | '/table-editor/edit'
    | '/finance/fraud/add'
    | '/finance/fraud/edit'
    | '/hr/leave/add'
    | '/hr/leave/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/logged-out'
    | '/login'
    | '/otp'
    | '/profile-settings'
    | '/reports'
    | '/reset-password'
    | '/user'
    | '/finance/assets'
    | '/finance/auctions'
    | '/finance/audit'
    | '/finance/fraud'
    | '/finance/fuel'
    | '/finance/missions'
    | '/finance/payments'
    | '/finance/petty-cash'
    | '/finance/procurement'
    | '/finance/stock'
    | '/finance/timesheets'
    | '/finance/travel'
    | '/finance/vehicles'
    | '/hr/compensation'
    | '/hr/disciplinary'
    | '/hr/leave'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/training'
    | '/table-editor/add'
    | '/table-editor/edit'
    | '/finance/fraud/add'
    | '/finance/fraud/edit'
    | '/hr/leave/add'
    | '/hr/leave/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/logged-out'
    | '/login'
    | '/otp'
    | '/profile-settings'
    | '/reports'
    | '/reset-password'
    | '/user'
    | '/finance/assets'
    | '/finance/auctions'
    | '/finance/audit'
    | '/finance/fraud'
    | '/finance/fuel'
    | '/finance/missions'
    | '/finance/payments'
    | '/finance/petty-cash'
    | '/finance/procurement'
    | '/finance/stock'
    | '/finance/timesheets'
    | '/finance/travel'
    | '/finance/vehicles'
    | '/hr/compensation'
    | '/hr/disciplinary'
    | '/hr/leave'
    | '/hr/performance'
    | '/hr/recruitment'
    | '/hr/training'
    | '/table-editor/add'
    | '/table-editor/edit'
    | '/finance/fraud/add'
    | '/finance/fraud/edit'
    | '/hr/leave/add'
    | '/hr/leave/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoggedOutRoute: typeof LoggedOutRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UserRoute: typeof UserRoute
  FinanceAssetsRoute: typeof FinanceAssetsRoute
  FinanceAuctionsRoute: typeof FinanceAuctionsRoute
  FinanceAuditRoute: typeof FinanceAuditRoute
  FinanceFraudRoute: typeof FinanceFraudRouteWithChildren
  FinanceFuelRoute: typeof FinanceFuelRoute
  FinanceMissionsRoute: typeof FinanceMissionsRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinancePettyCashRoute: typeof FinancePettyCashRoute
  FinanceProcurementRoute: typeof FinanceProcurementRoute
  FinanceStockRoute: typeof FinanceStockRoute
  FinanceTimesheetsRoute: typeof FinanceTimesheetsRoute
  FinanceTravelRoute: typeof FinanceTravelRoute
  FinanceVehiclesRoute: typeof FinanceVehiclesRoute
  HrCompensationRoute: typeof HrCompensationRoute
  HrDisciplinaryRoute: typeof HrDisciplinaryRoute
  HrLeaveRoute: typeof HrLeaveRouteWithChildren
  HrPerformanceRoute: typeof HrPerformanceRoute
  HrRecruitmentRoute: typeof HrRecruitmentRoute
  HrTrainingRoute: typeof HrTrainingRoute
  TableEditorAddRoute: typeof TableEditorAddRoute
  TableEditorEditRoute: typeof TableEditorEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-settings': {
      id: '/profile-settings'
      path: '/profile-settings'
      fullPath: '/profile-settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logged-out': {
      id: '/logged-out'
      path: '/logged-out'
      fullPath: '/logged-out'
      preLoaderRoute: typeof LoggedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-editor/edit': {
      id: '/table-editor/edit'
      path: '/table-editor/edit'
      fullPath: '/table-editor/edit'
      preLoaderRoute: typeof TableEditorEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-editor/add': {
      id: '/table-editor/add'
      path: '/table-editor/add'
      fullPath: '/table-editor/add'
      preLoaderRoute: typeof TableEditorAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/training': {
      id: '/hr/training'
      path: '/hr/training'
      fullPath: '/hr/training'
      preLoaderRoute: typeof HrTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/recruitment': {
      id: '/hr/recruitment'
      path: '/hr/recruitment'
      fullPath: '/hr/recruitment'
      preLoaderRoute: typeof HrRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/performance': {
      id: '/hr/performance'
      path: '/hr/performance'
      fullPath: '/hr/performance'
      preLoaderRoute: typeof HrPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave': {
      id: '/hr/leave'
      path: '/hr/leave'
      fullPath: '/hr/leave'
      preLoaderRoute: typeof HrLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/disciplinary': {
      id: '/hr/disciplinary'
      path: '/hr/disciplinary'
      fullPath: '/hr/disciplinary'
      preLoaderRoute: typeof HrDisciplinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/compensation': {
      id: '/hr/compensation'
      path: '/hr/compensation'
      fullPath: '/hr/compensation'
      preLoaderRoute: typeof HrCompensationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/vehicles': {
      id: '/finance/vehicles'
      path: '/finance/vehicles'
      fullPath: '/finance/vehicles'
      preLoaderRoute: typeof FinanceVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/travel': {
      id: '/finance/travel'
      path: '/finance/travel'
      fullPath: '/finance/travel'
      preLoaderRoute: typeof FinanceTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/timesheets': {
      id: '/finance/timesheets'
      path: '/finance/timesheets'
      fullPath: '/finance/timesheets'
      preLoaderRoute: typeof FinanceTimesheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/stock': {
      id: '/finance/stock'
      path: '/finance/stock'
      fullPath: '/finance/stock'
      preLoaderRoute: typeof FinanceStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/procurement': {
      id: '/finance/procurement'
      path: '/finance/procurement'
      fullPath: '/finance/procurement'
      preLoaderRoute: typeof FinanceProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/petty-cash': {
      id: '/finance/petty-cash'
      path: '/finance/petty-cash'
      fullPath: '/finance/petty-cash'
      preLoaderRoute: typeof FinancePettyCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/missions': {
      id: '/finance/missions'
      path: '/finance/missions'
      fullPath: '/finance/missions'
      preLoaderRoute: typeof FinanceMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fuel': {
      id: '/finance/fuel'
      path: '/finance/fuel'
      fullPath: '/finance/fuel'
      preLoaderRoute: typeof FinanceFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fraud': {
      id: '/finance/fraud'
      path: '/finance/fraud'
      fullPath: '/finance/fraud'
      preLoaderRoute: typeof FinanceFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/audit': {
      id: '/finance/audit'
      path: '/finance/audit'
      fullPath: '/finance/audit'
      preLoaderRoute: typeof FinanceAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/auctions': {
      id: '/finance/auctions'
      path: '/finance/auctions'
      fullPath: '/finance/auctions'
      preLoaderRoute: typeof FinanceAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/assets': {
      id: '/finance/assets'
      path: '/finance/assets'
      fullPath: '/finance/assets'
      preLoaderRoute: typeof FinanceAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/leave/edit': {
      id: '/hr/leave/edit'
      path: '/edit'
      fullPath: '/hr/leave/edit'
      preLoaderRoute: typeof HrLeaveEditRouteImport
      parentRoute: typeof HrLeaveRoute
    }
    '/hr/leave/add': {
      id: '/hr/leave/add'
      path: '/add'
      fullPath: '/hr/leave/add'
      preLoaderRoute: typeof HrLeaveAddRouteImport
      parentRoute: typeof HrLeaveRoute
    }
    '/finance/fraud/edit': {
      id: '/finance/fraud/edit'
      path: '/edit'
      fullPath: '/finance/fraud/edit'
      preLoaderRoute: typeof FinanceFraudEditRouteImport
      parentRoute: typeof FinanceFraudRoute
    }
    '/finance/fraud/add': {
      id: '/finance/fraud/add'
      path: '/add'
      fullPath: '/finance/fraud/add'
      preLoaderRoute: typeof FinanceFraudAddRouteImport
      parentRoute: typeof FinanceFraudRoute
    }
  }
}

interface FinanceFraudRouteChildren {
  FinanceFraudAddRoute: typeof FinanceFraudAddRoute
  FinanceFraudEditRoute: typeof FinanceFraudEditRoute
}

const FinanceFraudRouteChildren: FinanceFraudRouteChildren = {
  FinanceFraudAddRoute: FinanceFraudAddRoute,
  FinanceFraudEditRoute: FinanceFraudEditRoute,
}

const FinanceFraudRouteWithChildren = FinanceFraudRoute._addFileChildren(
  FinanceFraudRouteChildren,
)

interface HrLeaveRouteChildren {
  HrLeaveAddRoute: typeof HrLeaveAddRoute
  HrLeaveEditRoute: typeof HrLeaveEditRoute
}

const HrLeaveRouteChildren: HrLeaveRouteChildren = {
  HrLeaveAddRoute: HrLeaveAddRoute,
  HrLeaveEditRoute: HrLeaveEditRoute,
}

const HrLeaveRouteWithChildren =
  HrLeaveRoute._addFileChildren(HrLeaveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoggedOutRoute: LoggedOutRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UserRoute: UserRoute,
  FinanceAssetsRoute: FinanceAssetsRoute,
  FinanceAuctionsRoute: FinanceAuctionsRoute,
  FinanceAuditRoute: FinanceAuditRoute,
  FinanceFraudRoute: FinanceFraudRouteWithChildren,
  FinanceFuelRoute: FinanceFuelRoute,
  FinanceMissionsRoute: FinanceMissionsRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinancePettyCashRoute: FinancePettyCashRoute,
  FinanceProcurementRoute: FinanceProcurementRoute,
  FinanceStockRoute: FinanceStockRoute,
  FinanceTimesheetsRoute: FinanceTimesheetsRoute,
  FinanceTravelRoute: FinanceTravelRoute,
  FinanceVehiclesRoute: FinanceVehiclesRoute,
  HrCompensationRoute: HrCompensationRoute,
  HrDisciplinaryRoute: HrDisciplinaryRoute,
  HrLeaveRoute: HrLeaveRouteWithChildren,
  HrPerformanceRoute: HrPerformanceRoute,
  HrRecruitmentRoute: HrRecruitmentRoute,
  HrTrainingRoute: HrTrainingRoute,
  TableEditorAddRoute: TableEditorAddRoute,
  TableEditorEditRoute: TableEditorEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
